//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update_Histories
    {
        public int Id { get; set; }
        public Nullable<int> Notepad_Id { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public Nullable<int> Reminder_Id { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public int Uid { get; set; }
        public string Description { get; set; }
        public int Active { get; set; }
    
        public virtual Notepad Notepad { get; set; }
        public virtual Reminder Reminder { get; set; }
        public virtual Task Task { get; set; }
        public virtual Visual_Boards Visual_Boards { get; set; }
        public virtual User User { get; set; }
    }
}
